### ISSUE TITLE
java.lang.ClassNotFoundException: com.google.gson.JsonDeserializer

### ISSUE THREAD

**Issue by davidg95** [HexoCraft/AddLight#10]
Hi

We use your plugin AddLight-4.2.0 for our server, however whenever we type any command we get the following error-

We have metrics and worldedit installed.

```
[11:39:43 INFO]: Davidg_95 issued server command: /addlight help
[11:39:43 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'help' in plugin AddLight v4.2.0
        at com.github.hexocraft.addlight.api.command.Command.execute(Command.java:562) ~[?:?]
        at com.github.hexocraft.addlight.api.command.Command.execute(Command.java:577) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:625) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1058) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:919) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:656) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NoClassDefFoundError: com/google/gson/JsonDeserializer
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_112]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_112]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_112]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_112]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_112]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_112]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_112]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_112]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:193) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:73) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_112]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_112]
        at com.github.hexocraft.addlight.api.chat.Chat.sendMessage(Chat.java:56) ~[?:?]
        at com.github.hexocraft.addlight.api.chat.Chat.sendMessage(Chat.java:41) ~[?:?]
        at com.github.hexocraft.addlight.api.message.Message.sendToPlayer(Message.java:180) ~[?:?]
        at com.github.hexocraft.addlight.api.message.Message.send(Message.java:148) ~[?:?]
        at com.github.hexocraft.addlight.api.message.predifined.message.EmptyMessage.toSenders(EmptyMessage.java:49) ~[?:?]
        at com.github.hexocraft.addlight.api.command.predifined.CommandHelp.onCommand(CommandHelp.java:132) ~[?:?]
        at com.github.hexocraft.addlight.api.command.Command.execute(Command.java:558) ~[?:?]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonDeserializer
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_112]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_112]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_112]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_112]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_112]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_112]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_112]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_112]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_112]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_112]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:193) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:73) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_112]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_112]
        at com.github.hexocraft.addlight.api.chat.Chat.sendMessage(Chat.java:56) ~[?:?]
        at com.github.hexocraft.addlight.api.chat.Chat.sendMessage(Chat.java:41) ~[?:?]
        at com.github.hexocraft.addlight.api.message.Message.sendToPlayer(Message.java:180) ~[?:?]
        at com.github.hexocraft.addlight.api.message.Message.send(Message.java:148) ~[?:?]
        at com.github.hexocraft.addlight.api.message.predifined.message.EmptyMessage.toSenders(EmptyMessage.java:49) ~[?:?]
        at com.github.hexocraft.addlight.api.command.predifined.CommandHelp.onCommand(CommandHelp.java:132) ~[?:?]
        at com.github.hexocraft.addlight.api.command.Command.execute(Command.java:558) ~[?:?]
        ... 15 more
```

Thanks :)

**Comment by hexosse** [comment]
Sorry for the delay, I was on vacation.

So, your problem is because you are using bukkit or spigot **1.8** which don't include gson.
To solve your problem, download [gson](http://central.maven.org/maven2/com/google/code/gson/gson/2.8.1/gson-2.8.1.jar), then open it as a zip and copy all the content of gson-2.8.1.jar into you spigot.jar or into AddLight-4.2.0.jar.

Once gson will be in your classpath, your problem will be solved

**Comment by davidg95** [comment]
Perfect 😁😁

Thanks so much

David
