### ISSUE TITLE
Using `lightlevel` produces an error

### ISSUE THREAD

**Issue by separatio** [HexoCraft/AddLight#15]
Stack trace:
`org.bukkit.command.CommandException: Unhandled exception executing command 'lightlevel' in plugin AddLight v4.2.0
	at com.github.hexocraft.addlight.api.command.Command.execute(Command.java:562) ~[?:?]
	at com.github.hexocraft.addlight.api.command.Command.execute(Command.java:577) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1392) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1227) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542) ~[?:1.8.0_131]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_131]
	at com.github.hexocraft.addlight.commands.AlCommandLightlevel.onCommand(AlCommandLightlevel.java:74) ~[?:?]
	at com.github.hexocraft.addlight.api.command.Command.execute(Command.java:558) ~[?:?]
	... 16 more`

Not sure exactly how this happened, but I can provide some additional logs if you ping me.

**Comment by hexosse** [comment]
Didn't manage to reproduce it.
Could you give me more details.
Could you find a way to reproduce it?

**Comment by separatio** [comment]
Sorry for the delay. Definitely. I've also PM'ed you on Spigot. You can close this issue for now until I can reproduce it. Not sure how much time I'll have. The trace seems to be badly added too. Should've done a gist.
